### ISSUE TITLE
Handle infinite recursion cases?

### ISSUE THREAD

**Issue by domenic** [domenic/promises-unwrapping#1]
- [x] Use existing Promises/A+ technology here to handle `Resolve(p, p)`.
- [ ] Consider detecting infinite cycles.

**Comment by annevk** [comment]
Why is it more important to detect cycles here than with while(1)?

**Comment by domenic** [comment]
That's a fair question, and the answer may be that it's not. Fixing `Resolve(p, p)` is a clear win, as it's cheap and prevents `var p = fulfilledPromise.then(() => p)`. But full cycle detection is almost certainly more costly, and might not be a good idea.

To be clear, the scenario that cycle detection would solve would be

``` js
var p1 = fulfilledPromise.then(() => p2);
var p2 = fulfilledPromise.then(() => p1);
```

Cycle detection would consist of rejecting both `p1` and `p2` with an error (probably a `TypeError`).

**Comment by slightlyoff** [comment]
I don't see why this needs fixing at all. Devtools can detect it without any spec changes.

**Comment by domenic** [comment]
That's a great point. Closing.
