### ISSUE TITLE
Bad promise constructor arguments

### ISSUE THREAD

**Issue by domenic** [domenic/promises-unwrapping#10]
Assuming #8 is implemented and `Promise(x)` (without `new`) no longer coerces, what should the following do?
1. `Promise("5")`
2. `Promise(() => {})`
3. `new Promise("5")`

I am leaning toward "throw a `TypeError`" but an argument could be made for returning a new promise rejected with a `TypeError` instead.

**Comment by domenic** [comment]
@erights any thoughts on this?

**Comment by annevk** [comment]
Synchronously throwing here seems better as it's really just a typo.

**Comment by erights** [comment]
I agree with Anne. We avoid throws by using rejections to protect synchronous callers against data-dependent dynamic errors. These are just static bugs in the program, for which an early-as-possible error is good.

**Comment by domenic** [comment]
Sounds good, will make the change tonight.
