### ISSUE TITLE
Fulfilled vs. Resolved

### ISSUE THREAD

**Issue by bterlson** [domenic/promises-unwrapping#100]
The terminology currently employed here and in the ES6 spec draft is confusing to me. The three states are "pending", "fulfilled", and "rejected". The latter two states are considered "resolved" states. However, on the producer side, I use functions called "resolve" and "reject" to transition to the latter two states respectively, and the spec text often seems to talk about resolve and reject as mutually exclusive actions when, as currently defined, rejecting a promise also resolves the promise.

Would it make more sense to consider the three states "pending", "resolved", and "rejected", and refer to the "resolved" and "rejected" states collectively as "fulfilled" states (or some other term entirely)?

**Comment by domenic** [comment]
Please read ["States and Fates"](https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md). In specific:

> The latter two states are considered "resolved" states. 

Nope, they are considered "settled" states; a promise can be resolved but still pending.

> I use functions called "resolve" and "reject" to transition to the latter two states respectively

You don't transition to the resolve state by calling resolve; instead, you resolve a promise, which might put it in any of the three states (pending, fulfilled, rejected).

**Comment by bterlson** [comment]
Thanks for the pointers! I vote for copy/pasting that doc to the top of #sec-promise-objects :) I still find the language difficult to reason about in places, but I think I can manage now. Perhaps part of the confusion was also due to this signature in the ES6 spec draft: "PromiseThen (promise, resolvedAction, rejectedAction)".

**Comment by bterlson** [comment]
Oh, also, in case you're looking to beef up the prose, in addition to the distinction between state (fulfilled, rejected, pending) and fate (resolved, unresolved), I also missed the distinction between [[PromiseStatus]] (undefined, unresolved, has-resolution, has-rejection) and state.

**Comment by domenic** [comment]
Hopefully most of these confusions will go away with the simplifications of #99, since it becomes much less important to track resolution separately. The verb "resolve" will still be there, along with the corresponding spec operation, but e.g. `[[PromiseStatus]]` should be able to become `[[PromiseState]]` and most other internal things that react to resolution will be able to instead react to fulfillment.

**Comment by shannonmoeller** [comment]
I agree that using "resolved" and "fulfilled" interchangeably is confusing and inconsistent.

(Sorry for commenting on an ancient issue, but I was about to create one regarding this and saw that it had already been created.)
