### ISSUE TITLE
catch() vs fail()

### ISSUE THREAD

**Issue by daveheitzman** [domenic/promises-unwrapping#101]
I was disappointed to learn that Promise#fail is likely to be replaced in e6 with Promise#catch. 

fail() Is already being used in a lot of promise code. 

Also, it seems that #catch() is being used to assign a function to handle a failed network request, which is a different thing than #catch() typically implies - handling an exception. 

I'd like to lobby for keeping fail() in the spec if it's not too late.

**Comment by domenic** [comment]
It was never in the spec, and TC39 never wanted it. It will not be added to the spec.

**Comment by cscott** [comment]
Adding convenience methods is more appropriate for libraries like https://github.com/cscott/prfun at this point.

I'm not a huge fan of `fail`, though -- it's just a hack to work around old browsers that forced you to write `p['catch']` instead of `p.catch`.  It seems like it's pretty easy to do `Promise.prototype.fail = Promise.prototype['catch'];` at the top of your file if that's important to you.

**Comment by stefanpenner** [comment]
@cscott yup, exactly. Also a quick es5 -> es3 transpile before shipping can take care of it, and others

**Comment by daveheitzman** [comment]
My gripe stems from the fact that the RSVP library (https://github.com/tildeio/rsvp.js) is now deprecating Promise#fail() because they want to support the e6 standard, which is understandable. This now works its way downstream into ember and ember-data, which is how I came across it. 

I can shim libraries all I want which I could also do if the functions were named a, b and q. I'm arguing that including Promise#fail in the standard is a good idea. 

At some point in the future, ecma 6 will be so widely distributed that people can reliably write promises in plain old javascript. Until that point, they will use js libraries, like RSVP and jquery. 

I wonder if the adoption of 'catch' will become standard in the js libraries by that point.

**Comment by cscott** [comment]
Use `es6-shim`/`prfun` instead of RSVP and you can start living in the future, today! ;)

**Comment by stefanpenner** [comment]
We need to start adoption sometime. Now is less painful then the future

**Comment by stefanpenner** [comment]
@cscott I'm curious what part of RSVP isn't aligned with the "future" ? All see with `prfun` is lots of non-standard extensions.

**Comment by cscott** [comment]
It is a Promise implementation.

**Comment by daveheitzman** [comment]
stefan I think he's just saying that with the shim I can use "native" promises right now. .. except es-shim is a 570 K  file, unzipped.  not exactly practical..  makes more sense to use RSVP until 10 more years go by. 

I can't believe the committee went with "catch()". It's this sort of misguided attempt at alignment.. but which has no practical use and obscures the meaning of the methods involved. I mean, suppose I thought promises ought to use the "switch" statement as their template.. Okay so I call Promise.switch() to make the network request, then case("success", function(msg){}).case("retry", function(){})  

It starts not making sense as I mash my intentions against the metaphor provided by java syntactical constructs. 

Oh well.. 

Any bets on when one can reliably ship js apps that rely on native promises, ie, when 80% of the installed browser base will be es6 or greater?

**Comment by cscott** [comment]
@daveheitzman es6-shim is 68k, unzipped or minified.  prfun is 16k, unzipped or minified.

You probably should read up on Promises some more.  The `catch` name is not a "misguided attempt at alignment" but a direct correlation.  You can mechanically transform synchronous code into asynchronous code with identical try/catch/finally semantics.

Both Chrome and Firefox have native Promises, now.  If you look at the tables at http://www.w3schools.com/browsers/browsers_stats.asp you will discover that the future will arrive very quickly.  Firefox and Chrome account for > 80% of browsers, so for purpose of discussion let's ignore the others.  Chrome's current release is 34 and [only 15% of its users are more than 3 releases back](http://www.w3schools.com/browsers/browsers_chrome.asp).  So we can expect in three more Chrome releases 85% of Chrome users will have native Promises.  Firefox's current release is 28 and [only 22% of its users are more than 3 releases back](http://www.w3schools.com/browsers/browsers_firefox.asp).  So within 3 releases we can expect native Promises in ~70% of browsers, very conservatively.  (The proportion will be higher if Chrome continues its browser share growth, Safari picks up native promises from v8, etc).

According to [Chrome's current release cycle](http://www.chromium.org/developers/calendar), Chrome 37 will be released in June 2014.   According to [Firefox's release cycle](https://wiki.mozilla.org/RapidRelease/Calendar), Firefox 31 is due July 22, 2014.  So you can expect >70% browsers will have native Promises by the end of this summer.

And, of course, you can start using them today using `es6-shim`.

**Comment by petkaantonov** [comment]
.fail is very bad, it is associated with the thinking that promises are just an alternative style to callbacks where the error and success "callbacks" are just attached separately.

.catch has a better chance of making it clear that the point of promises is to be a DSL for asynchronous code, not just an alternative way to attach callbacks.

**Comment by daveheitzman** [comment]
Thanks for the information guys. Very good points. Maybe I am convinced.. we'll see.
