### ISSUE TITLE
promise.prototype.thenReturn()

### ISSUE THREAD

**Issue by jonathanong** [domenic/promises-unwrapping#115]
is there a spec for bluebird's version of this?

**Comment by domenic** [comment]
No. It is a nonstandard Bluebird extension.

**Comment by cscott** [comment]
Fwiw, the `prfun` npm package implements many bluebird extensions on top of
standard ES6 promises.

**Comment by jonathanong** [comment]
@domenic are there plans to add more features like this to the promises spec or is the promise API locked like it's node.js? i know there's enough shit to deal with for es6

**Comment by stefanpenner** [comment]
Frozen for es6

**Comment by jonathanong** [comment]
i mean for es7+

**Comment by domenic** [comment]
Unclear, I want to add Promise.prototype.finally at least, but getting consensus on ES stuff is hard :-/

**Comment by stefanpenner** [comment]
Finally is quite important for real life scenarios, much more then race :trollface: 

Atleast it's easy to polyfil, but hopefully it comes in officially sometime soon
