### ISSUE TITLE
Grammar in States and Fates

### ISSUE THREAD

**Issue by kidplug** [domenic/promises-unwrapping#118]
I don't understand this line - is it a typo?

>  A promise is resolved if trying to resolve or reject it has no effect, ...

**Comment by domenic** [comment]
No. What do you not understand?

**Comment by kidplug** [comment]
the grammar of the first half of the sentence prior to the comma...
specifically: "it has no effect".  Do you need a comma or something in
there... ?

> A promise is resolved if trying to resolve or reject it has no effect, i.e. the promise has been "locked in" to either follow another promise, or has been fulfilled or rejected.

On Fri, Sep 25, 2015 at 10:01 AM, Domenic Denicola <notifications@github.com

**Comment by kidplug** [comment]
Oh I think I'm getting you now.

A promise is resolved, if WHEN you try to resolve or reject there is no resulting effect....

is that right?

**Comment by kidplug** [comment]
I think the "it" was unclear - was "it" the promise?  No - "it" meant your action...

**Comment by domenic** [comment]
Yep!

**Comment by kidplug** [comment]
Thanks for your replies!
