### ISSUE TITLE
UpdateDerived insufficiently asynchronous

### ISSUE THREAD

**Issue by erights** [domenic/promises-unwrapping#14]
Diagnosis and fix at

http://esdiscuss.org/topic/ap2-bugs
https://mail.mozilla.org/pipermail/es-discuss/2013-August/033043.html

seem correct to me.

**Comment by domenic** [comment]
This is invalid. `CallHandler` queues a microtask, but his sample implementation of `CallHandler` does not, leading to the observed bug.

**Comment by Nathan-Wall** [comment]
Ok, making CallHandler asynchronous does solve the issue as well.  In that case, what is the purpose of "queue a microtask" in step 2.1 in UpdateDerived? Is it still necessary?

**Comment by domenic** [comment]
It's necessary since accessing `then` could trigger user code, if `then` were a getter, and additionally we need to call `then` in a new execution context anyway. @erights can explain in more depth why it's important for user code to always execute in a fresh execution context.

**Comment by Nathan-Wall** [comment]
Got it. Thanks!
