### ISSUE TITLE
Should we include Promise.async ?

### ISSUE THREAD

**Issue by erights** [domenic/promises-unwrapping#17]
What about Promise.async http://wiki.ecmascript.org/doku.php?id=strawman:async_functions#reference_implementation ? Given the feedback we've been hearing about how wonderful async functions are in C# (and F#, etc), and given how quickly generators are coming, I think the need for this is more pressing.

**Comment by erights** [comment]
Note that the implementation at that link is out of date -- it is from the days of StopIteration. It needs to be updated for modern ES6 generators.

**Comment by domenic** [comment]
I am tempted, but on the other hand, it might end up being just vestigial in an ES7 world where promises get dedicated syntax of some sort. (In fact, it might be considered bad practice in such a world.)

**Comment by annevk** [comment]
Given that, I suggest we hold off on this until at least the basic design is deployed. We can then evaluate this for an upgrade to that.

**Comment by domenic** [comment]
Let's close this for now then.
