### ISSUE TITLE
Add shorthand "prose hooks" for performing various operations

### ISSUE THREAD

**Issue by domenic** [domenic/promises-unwrapping#21]
People seem confused, and want to know how they can do `Promise.reject` or `Promise.all` in their specs. It's pretty straightforward; you say:

> Let `x` be the result of `Promise.reject(r)`, using the initial value of `Promise.reject`.

But we may want to provide some easy phrases that are shorthand for this longhand. Here's what I can think of:
- a promise resolved with x (e.g. "return a promise resolved with x," "let p be a promise resolved with x")
- a promise rejected with r
- cast x to a promise
- let p be a newly-created promise object (the ES spec already uses this as shorthand for some crazy `@@create` stuff)
- resolve p with x
- reject p with r
- let p be the result of (racing p1, p2, p3 / racing iterableOfPromises)
- let p be the result of waiting for all of (p1, p2, p3 / iterableOfPromises) (any better phrasing?)

**Comment by annevk** [comment]
- Let p be the first of p1, p2, p3
- Let p be all of p1, p2, p3

**Comment by tabatkins** [comment]
"be the first of" is extremely ambiguous in English - it sounds like it's just referring to p1 in a stupid way.  I prefer Domenic's wording.

Same with "let p be all of ..." - sounds like it's just collecting them into a list or something.  "waiting for all" it a little long, but it's clear and easy to remember, so I'm fine with it.

**Comment by domenic** [comment]
Added a guide with these plus some guidance and examples. Could probably use more examples; pull requests welcome in that department.
