### ISSUE TITLE
Promise(resolver) vs .then(resolve, reject)

### ISSUE THREAD

**Issue by johnjbarton** [domenic/promises-unwrapping#22]
As a developer I find the disconnect between the constructor and .then() functions puzzling and annoying. 

The constructor take an object as an argument with properties .resolve and .reject; then() takes two arguments called resolve and reject. 

Calling the current constructor with a syntax consistent with then() results in a very puzzling runtime error message deep in the Promise library.  Definitely not ergonomic.

**Comment by domenic** [comment]
This repo has always used the two-argument form, so I am not sure what the issue is? https://github.com/domenic/promises-unwrapping#promiseresolver step 9 in particular.

Older DOM promises had a `PromiseResolver` object, but this repo has always had `(resolve, reject)`.

**Comment by johnjbarton** [comment]
Oh, sorry. I was using https://github.com/slightlyoff/Promises, I thought it matched this spec.
