### ISSUE TITLE
Don't coerce Promise in UpdateDerived

### ISSUE THREAD

**Issue by 6XGate** [domenic/promises-unwrapping#43]
Would it not be more favorable update with a derived promise when originator.[[Value]] is already a Promise rather than try to coerce it as a Thenable/Promise-like.

**Comment by 6XGate** [comment]
A diff of the README.md:

```
116c116,118
<       1. If `ThenableCoercions.has(originator.[[Value]])`,
---
>       1. If `IsPromise(originator.[[Value]])`,
>          1. Call `UpdateDerivedFromPromise(derived, originator.[[Value]])`.
>       1. Otherwise, if `ThenableCoercions.has(originator.[[Value]])`,
```

**Comment by domenic** [comment]
It's impossible for `originator.[[Value]]` to ever be a promise; see the `Resolve` algorithm.

(Or, if you can produce a counterexample piece of code, that's a bug, and I'll reopen so we can fix it!)
