### ISSUE TITLE
Drop dot notation for internal data properties

### ISSUE THREAD

**Issue by Nathan-Wall** [domenic/promises-unwrapping#49]
See https://mail.mozilla.org/pipermail/es-discuss/2013-October/033962.html .  Specifically Allen's statement "The dot notation is never used in the spec to refer to internal data properties."

Example from current draft (taken from `IsPromise`):

> Return true if IsObject(x) and x.[[IsPromise]] is true.

I don't know what the correct notation would be, but `[[IsPromise]]` is an internal data property, so should probably not be accessed with dot notation.

This may have just been a notational convenience and something you intended to change later, but I didn't see a ticket for it so thought I would file one to help catch it early rather than later.

Great job so far, by the way!

**Comment by domenic** [comment]
Yeah, related to #34, but giving it its own issue makes sense.

**Comment by domenic** [comment]
Fixed by tonight/this morning's commits.
