### ISSUE TITLE
Never bypass the `then` method

### ISSUE THREAD

**Issue by domenic** [domenic/promises-unwrapping#53]
### Proposal
- Move the contents of the Then abstract operation into the `Promise.prototype.then` method definition.
- Everywhere we use the Then abstract operation, replace it with a call to the respective `then` method.
  - Promise.all
  - Promise.race
  - Promise.prototype.then's recursive case
### Observable Changes
- This makes overriden `then`s govern the behavior of a promise, e.g.
  
  ``` js
  const p = new Promise(() => {});
  p.then = f => f(5);
  Promise.all([p]).then(([x]) => console.log(x)); // logs 5
  ```
- This forces implementations to make an observable call to `then` instead of using internal mechanisms. I imagine this will not actually be a burden.
- This does not impact `Promise.resolve` yet, i.e.
  
  ``` js
  const p = new Promise(r => r(1));
  p.then = f => f(2);
  Promise.resolve(p).then(x => console.log(x)); // still logs 1 right now
  ```
  
  for that, see #54.

**Comment by domenic** [comment]
@erights would appreciate your feedback before I implement this change; assigning to you.

**Comment by erights** [comment]
> assigning to you

accepted. Need to think about this. I will point out that

```
p.then = ....
```

fails if p is frozen. If the assignment is in strict code, it fails noisily.
