### ISSUE TITLE
iterable should be transformed to an iterator

### ISSUE THREAD

**Issue by Nathan-Wall** [domenic/promises-unwrapping#58]
It looks like places in the ES6 draft where a function takes an iteratable, it converts it to an iterator before passing to `IteratorStep`.  Should similar steps be taken in `Promise.all` and `Promise.race`?

For example, see [Map](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-map-iterable-comparator), step 7:

```
a. Let iter be the result of GetIterator(iterable).
b. ReturnIfAbrupt(iter).
```

Then `iter` is passed to `IteratorStep`.

**Comment by domenic** [comment]
Good call, thanks!
