### ISSUE TITLE
PropagateToDerived should not have to ReturnIfAbrupt

### ISSUE THREAD

**Issue by jorendorff** [domenic/promises-unwrapping#60]
The ReturnIfAbrupt call in the loop in PropagateToDerived looks awfully suspicious to me. It's important to finish, and it's important not to reenter, so returning abruptly there should never happen.

It looks like UpdateDerived is infallible; anything that could fail is scheduled for a later microtask. So I think the ReturnIfAbrupt call can just be removed.

**Comment by domenic** [comment]
> It looks like UpdateDerived is infallible; anything that could fail is scheduled for a later microtask.

I believe this is correct; I remember when adding the ReturnIfAbrupts that I was unsure about its utility in this case.

> So I think the ReturnIfAbrupt call can just be removed.

Sounds like a plan, thanks.
