### ISSUE TITLE
Long stack traces

### ISSUE THREAD

**Issue by cowwoc** [domenic/promises-unwrapping#70]
Does the spec support "long stack traces" as defined by https://github.com/kriskowal/q#long-stack-traces? If not, I believe it's essential for troubleshooting to add this feature. If it can be implemented efficiently by browsers, then it should be on by default, otherwise it can be disabled by default, but either way the feature be required.

**Comment by domenic** [comment]
Yeah, there should be nothing preventing browsers from implementing this. Language-level specs don't generally govern debugging experiences, so it's not something we'd explicitly include here, but you're right to be sure it's at least possible.

**Comment by cowwoc** [comment]
Okay. I've opened https://code.google.com/p/chromium/issues/detail?id=313297 so you can close this issue.
