### ISSUE TITLE
Promise Reaction Functions and Promise Resolution Handler Functions don't need to be real functions

### ISSUE THREAD

**Issue by domenic** [domenic/promises-unwrapping#78]
As discussed over email with @allenwb, it is not a good idea to specify creation of unobservable function objects. Instead we should revert to the earlier strategy (pre 002ec7a25a97c70eb131096bd3f39da26c6d87c4) of passing around records.

As he says:

> If there is only a single abstraction operation that is ultimately going to be called you can just pass around an internal record containing the values you need to use as parameters and at the ultimate call site, pass the record or individual values when you call the abstract operation.  If there are several alternative abstraction operations that might be called you can pass an additional value in the record that selections which abstract operation you want to call.

We can probably also eliminate Identity Functions and Thrower Functions by passing around flags (this'll get ugly).

I do not believe this has any normative consequences.
- [x] Promise Reaction Functions
- [x] Promise Resolution Handler Functions
- [ ] Identity Functions
- [ ] Thrower Functions

**Comment by domenic** [comment]
@allenwb I believe you've been incorporating promises-unwrapping into the draft, at least according to some of your recent comments in other issues. Did you take on this task? I don't want to duplicate effort if so. But I'm happy to do it myself otherwise.

**Comment by allenwb** [comment]
Yes, I have now integrated promises into the ES6 draft spec. based upon the promises-unwrapping.  I have a couple of editorial tweaks to finish up this morning.  when those are done I'll send you a copy to review.

Allen

**Comment by domenic** [comment]
@allenwb do you still think it's important to factor out the Thrower and Identity functions? I can do this fairly easily now that things are much simpler. I'd just expand PromiseReaction's [[Handler]] field to be either a function or `"identity"` or `"thrower"` and then switch on the behavior instead of calling it inside PromiseReactionTask.

**Comment by domenic** [comment]
Ping @allenwb

**Comment by allenwb** [comment]
Yes, eliminating the functions sound like a good idea.
