### ISSUE TITLE
Missing completion values

### ISSUE THREAD

**Issue by anba** [domenic/promises-unwrapping#81]
Completion values are missing for the following functions:
- Promise.all Countdown Functions
- Reject Promise Functions (note: `PromiseReject` does not return a completion record)
- Resolve Promise Functions (note: `PromiseResolve` does not return a completion record)

**Comment by domenic** [comment]
Nice find. Isn't there some implicit `undefined` completion value escape hatch, though?

**Comment by anba** [comment]
The only shorthand currently defined is just the plain `Return` without any value (cf. 6.2.2.2).
