### ISSUE TITLE
Promise constructor: Handing of synchronous  of resolver exceptions 

### ISSUE THREAD

**Issue by allenwb** [domenic/promises-unwrapping#88]
Line 14 of the Promise constructor spec. translates any uncaught exceptions thrown by the resolver function into a rejection of the promise.  The Promise object is then returned normally from the constructor.

Why? It seems that the most likely situation is that such exceptions indicate a synchronous problem in initiating the deferred action rather than a problem within the deferred action (represented by the Promise) itself.  It would be better to immediately report such synchronous problems rather than delaying (and possibly loosing) them until a future pending 'then' is settled.

Also, there seems to be an inconsistency between  implicitly turning resolver exceptions into rejections when there is no mechanism for implicitly fulfilling the promise.  Consider a trivial  Promise constructor call:

``` javascript
new Promise( () => 10 / n)
```

This probably doesn't do what the programmer intended unless n is 0. They probably really meant: 

``` javascript
new Promise( resolve => resolve(10 / n))
```

or more explicitly:

``` javascript
new Promise( (resolve, reject) => {
     try {resolve(10 / n)} catch(e) {reject(e)}
})
```

Essentially we've provided a short cut handling writing the exceptional case while there is no available short cut for the normal case.

Does anyone have a strong reason for why unhanded exemptions in the resolver shouldn't cause abrupt completion of the constructor call?

**Comment by kriskowal** [comment]
In my experience, it is normal to consolidate the synchronous into asynchronous error handling code. In any function that returns a promise, I will frequently begin all actual work in a handler to ensure that all errors subsumed by the promise. In my opinion, the ability to implicitly subsume errors is the primary advantage of the `Promise` constructor over the `Q.defer()` style interface.

**Comment by domenic** [comment]
Agreed. More when I'm back at a computer, but this makes several patterns much easier, e.g. as in https://gist.github.com/domenic/7706162. It's pretty well-tested by now and works great in practice.

**Comment by allenwb** [comment]
OK, I'll accept that unifying handler of sync and async errors is convenient (with the caveat that it increases the chance of other errors (a missing then)  resulting in silently eating some originally synchronous exceptions).

**Comment by domenic** [comment]
People keep saying silently eating them... In my mind, a web console which doesn't surface unhandled rejections should be considered just as incomplete as one that doesn't surface unhandled exceptions, and just as unlikely to ship.

**Comment by allenwb** [comment]
How would a console discover unhandled rejections? the rejection and its associated exception are just state captured in a Promise object and if that object gets GC'ed nobody including a console is likely to have any visibility of it. In terms of mechanism this is very different from what happens with an unhandled exception.

**Comment by stefanpenner** [comment]
How I deal with unhandled rejection programmer ergonomic issues:

rsvp's `on('error` allow us to to provide somewhat useful tooling: https://github.com/tildeio/ember-extension/pull/76 which can raise awareness of unhandled on-next-turn exceptions.

Another example for printing to the console + working with the chrome debug tools.

``` js
RSVP.on('error', function(error) {
  // is invoked if a rejection occurs, and its not handled within the
  // same turn of the event loop.

  // optionally, only for errors
  // if (error instanceof Error) { console.assert(false, error); }

  console.assert(false, error);

  if (error && error.stack) {
    // console.error provides clickable stack-traces in chrome debugger
    console.error(error.stack);
  }
});
```

**Comment by domenic** [comment]
If the object gets GCed then nobody will ever handle the exception, so that's a good time to log the rejection to the console. But preferably it should be logged before then too, and removed from the console if/when it gets handled.

**Comment by stefanpenner** [comment]
@domenic ya, I think "on GC" would be a good last-resort hook.

**Comment by allenwb** [comment]
@domenic that would require making Promises finalizable objects, which is something that should be avoided in many high perf collector designs.  Particularly for high highly ephemeral objects, which seems likely to be the case for many Promises (such as all those promises returned by then methods).

**Comment by domenic** [comment]
Well, I'm not really sure what the right framework for thinking about it from a GC design perspective is; perhaps @jorendorff can comment, since he added that feature to Firefox's promises I believe. Maybe it is a weaker version of the feature that does not have the drawbacks you mention? The idea isn't deterministic notification of unhandled rejections; as @stefanpenner said, it's a last-resort hook of sorts. In the course of normal operation you would simply track a live list of unhandled rejections and surface that in the console UI, e.g. as is done in Q today using hackery (i.e. the fact that consoles sometimes live-update arrays that you log to them). The GC hook just lets you know a case when the rejection will definitely never be handled, and so perhaps should be surfaced more loudly.

**Comment by erights** [comment]
Only those promises that are in an unobserved rejected state need to generate notifications on GC. And it cannot be a requirement anyway, just a quality of implementation issue, since GC is never guaranteed for anything.
