### ISSUE TITLE
CountdownHolder setup is not robust in the face of broken promises

### ISSUE THREAD

**Issue by bzbarsky** [domenic/promises-unwrapping#89]
Looking at Promise.all, if the page sets Promise.prototype.then to a function that just immediately invokes the argument it was passed a bunch of times, then management of the countdown will get all confused.  In particular, you can end up resolving the returned promise before you've even finished going through the entire input list, you can end up resolving it after you've gone through the whole list but before all the promises have been resolved, etc.

It seems like things would be saner if Countdown Function had a boolean flag that made it a no-op after the first time it called.

**Comment by bzbarsky** [comment]
And in particular, as this is defined right now, you can actually call deferred.[[Resolve]] multiple times, because you can bounce the countdown to 0, then go through more of the list, then bounce it to 0 _again_.  But I _think_ [[Resolve]] protects against multiple calls.

**Comment by domenic** [comment]
Resolving twice is a no-op, so it should be fine as-is. I'm trying to figure out what the practical upside would be to protecting against this...

**Comment by bzbarsky** [comment]
The practical upside would be to guaranteee that Promise.all([a, b, c]) actually resolves its return promise with a three-element array.  Right now it does not guarantee that.

**Comment by domenic** [comment]
Ah yes, that'd be important; thank you. OK, sounds like a fix is in order. Coming up shortly...

**Comment by anba** [comment]
If you manually call the Promise.all Countdown Function, you can do four things:
- Prevent countdownHolder.[[Countdown]] from ever reaching zero
- Promise from Promise.all is resolved before arguments
- Promise from Promise.all is resolved despite rejected promise in arguments
- Promise.all calls resolver twice

Test cases available at [anba/es6draft/master/src/test/scripts/suite/objects/Promise/all.js#L57-L160](https://github.com/anba/es6draft/blob/master/src/test/scripts/suite/objects/Promise/all.js#L57-L160).

**Comment by bzbarsky** [comment]
Oh, nice catch...

So I think what we probably need to do is something like this (or equivalent):

1)  Make the Countdown Function only do the decrement once.
2)  Start off countdownHolder.[[Countdown]] with a value of 1, not 0, so that broken "then" implementations can't force a resolution before we've processed all the arguments.
3)  Increment countdownHolder.[[Countdown]]  _before_ invoking "then".
4)  At the end of all() decrement countdownHolder.[[Countdown]]  and if it's 0 try to resolve the promise.

**Comment by cscott** [comment]
Commit 280230d0d20ec1eac96278505391e5315145f8d5 (helpfully cited by github above) includes my fixes for `Promise.all()` in `es6-shim`.  They are basically @bzbarsky's suggestions exactly.  (Note that I had done his step 3 in my initial implementation, so that doesn't show up in the diff but it's there.)

**Comment by domenic** [comment]
Fixed over here and filed as https://bugs.ecmascript.org/show_bug.cgi?id=2579 for @allenwb.
