### ISSUE TITLE
Update with "This proposal has progressed to the Draft ECMAScript 6 Specification..."

### ISSUE THREAD

**Issue by rwaldron** [domenic/promises-unwrapping#96]
@domenic I pinged you IRC but figured I'd file here as well...

> Please add something similar to the "This proposal has progressed to the Draft ECMAScript 6 Specification..." (as seen here: http://wiki.ecmascript.org/doku.php?id=harmony:arrow_function_syntax)

**Comment by domenic** [comment]
Thanks Rick, will do. The situation is a bit different here than the wiki because as per #91 we plan to continue evolving here. But it's definitely important to note what the distinct roles of this document versus the official spec are.

**Comment by rwaldron** [comment]
>  we plan to continue evolving here.

Good luck with that :P
