### ISSUE TITLE
Implement January consensus: simplify resolution

### ISSUE THREAD

**Issue by domenic** [domenic/promises-unwrapping#99]
Due to the January consensus of removing flatMap from the future roadmap, we can drastically simplify the internals of the specification. I am excited.

**Comment by juandopazo** [comment]
Sadly, there was consensus in the meeting, but there were members not present who still disagree.

**Comment by allenwb** [comment]
is there an ETA for this update.  I want the pending ES draft to reflect the January concensus

**Comment by domenic** [comment]
Unfortunately I cannot work on this until after Monday. Realistically that would mean the 31st at the latest, or possibly in the 25th--26th range if I can buckle down and find some time during the week.

**Comment by domenic** [comment]
@allenwb FYI I have made significant progress on this work over the weekend and hope to finish the rest on my plane ride tonight.

**Comment by domenic** [comment]
I think this is done. All tests pass etc.
- [Diff](https://github.com/domenic/promises-unwrapping/compare/january-simplification?name=january-simplification#diff-04c6e90faac2675aa89e2176d2eec7d8)
- [Rendered version](https://github.com/domenic/promises-unwrapping/blob/61ebe654144e3ef0b1119fedec2eb3ac602b29b2/README.md)

I haven't squashed and merged into master yet because I want to review it with fresh eyes tomorrow and see if there are any tweaks that could be made to simplify or improve clarity. Also I could probably complete #78 by killing Identity and Thrower functions without much more effort.

But yeah, there you go. A big improvement IMO. The underlying concepts shine through much more clearly.

**Comment by juandopazo** [comment]
Is it not unwrapping on `then` anymore?

**Comment by cscott** [comment]
@juandopazo I see unwrapping at https://github.com/domenic/promises-unwrapping/compare/january-simplification?name=january-simplification#diff-04c6e90faac2675aa89e2176d2eec7d8R149

@domenic I'll try to update the `es6-shim` implementation this weekend (maybe after you finish #78?) to double-check your work.
